let clock = new Date()
let date = clock.getDate()
let hours = clock.getHours()
let min = clock.getMinutes()
let sec = clock.getSeconds()
console.log(date)
console.log(hours)
console.log(min)
console.log(sec)