let a = 45;
let b = "Ankit";
let c = null;
let d = true;
let e = BigInt("3212") + BigInt("3000");
let f = Symbol("This is Symbol");
let g = undefined;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof e);
console.log(typeof f);
console.log(typeof g);
